sudo: true
dist: bionic
language: python
cache: apt

addons:
  apt:
    packages:
      - tree
      - latexmk
      - biber
      - make

install:
    - pip install GitPython
      
script:
    - export COMMIT_MSG=$(python3 -c 'from git_version import get_deploy_message; print(get_deploy_message())'
    - python3 -c 'from build import build; build("build/LatexPackages/")'
    - cd build
    - zip -r LatexPackages.zip LatexPackages
    - tree -H '.' -I "index.html" -D --charset utf-8 -T "LatexPackages" > index.html
    - cd ..

after_success:
    

deploy:
    - provider: pages
      skip-cleanup: true
      github-token: $GITHUB_TOKEN
      local-dir: build/
      keep-history: false
      on:
        branch: master
    - provider: releases
      api_key: $GITHUB_TOKEN
      skip_cleanup: true
      file: $TRAVIS_BUILD_DIR/build/LatexPackages.zip
      on:
          tags: true
    - provider: pages
      edge: true
      github-token: $GITHUB_TOKEN
      local-dir: build/LatexPackages
      repo: kesslermaximilian/LatexPackagesBuild
      commiter_from_gh: true
      allow_empty_commit: true
      target_branch: $TRAVIS_BRANCH
      commit_message: $COMMIT_MSG
      on:
          all_branches: true
          condition: $TRAVIS_PULL_REQUEST = false
